
version: 3.0.0.{build}.{branch}
  
init:
  - git config --global core.autocrlf true
  
before_build:
 - cmd: dotnet restore TagHelperSamples\TagHelperSamples.sln

build_script:
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Authorization
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Bootstrap
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet publish TagHelperSamples\src\TagHelperSamples.Web
 
artifacts:
 - path: '\TagHelperSamples\src\TagHelperSamples.Web\bin\Debug\netcoreapp3.0\publish'
   name: WebSite
   type: WebDeployPackage


test_script:
 - ps: cd .\TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet test 
